version: '3'
services:
    web:
        restart: always
        build: .
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=app.py
        depends_on:
            - db
    db:
        restart: always
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=postgres
        volumes:
            - ./postgres-data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    migration:
        restart: on-failure
        image: jbergknoff/postgresql-client
        environment:
            - PGPASSWORD=123
        entrypoint: "psql -h db -U postgres -d postgres -a -f /migration.sql"
        volumes:
            - ./migration.sql:/migration.sql